name: AutoGod
version: 1.3
main: com.comonier.autogod.AutoGod
api-version: '1.21'
description: AutoGod and Fly plugin with independent persistence and group verification.
author: comonier
softdepend: [Vault]

commands:
  godme:
    description: Toggle your own God mode.
    permission: autogod.command.god
  flyme:
    description: Toggle your own Flight mode.
    permission: autogod.command.fly
  autogod:
    description: Administrative command for reloading.
    usage: /autogod reload
    permission: auto.god.admin

permissions:
  auto.god.admin:
    description: Allows reloading the plugin configuration.
    default: op
  autogod.command.god:
    description: Allows the use of /godme command.
    default: op
  autogod.command.fly:
    description: Allows the use of /flyme command.
    default: op
  auto.god.login:
    description: Receive God automatically on login.
    default: op
  auto.fly.login:
    description: Receive Fly automatically on login.
    default: op
